### ISSUE TITLE
Tutorial example 2 - some kind of temporary variable error

### ISSUE THREAD

**Issue by Gamewise** [JoshuaGrams/tiny-qbn#2]
This is the error I'm getting in your example: ![image](https://user-images.githubusercontent.com/63534513/93707842-2ba1f080-fb75-11ea-8830-3bf1ee82f87e.png)

I'm also getting my own errors when trying to replicate.. ;P But I thought I'd mention it because if you've got a working version I can just compare and see where I went wrong. 

The tutorials are great, but if there were some more screenshots along the way that would be so awesome.

**Comment by JoshuaGrams** [comment]
Oh dear.

So...that error says that `_products` is undefined.

Looks like it should be: `<<unset _product>>`  to clear the product flag, but I wrote `<<unset _products>>` and deleted the list of available products instead.

Oof. That has been broken for most of this year. Guess I didn't test before I uploaded.

**Comment by JoshuaGrams** [comment]
Do you have thoughts about what sort of screenshots would be useful? I wanted to make sure that I provided the code in text form so it was accessible to screenreaders, and was a little reluctant to duplicate that too much in screenshots, but...

Also if you save the runnable example page you can import it into Twine and look at all the code there. I should probably make a big flashing banner somewhere saying that, because I don't think that's general knowledge...

**Comment by Gamewise** [comment]
Haha no worries. I knew it would be something tiny that you'd spot straight
away hehe.

I think TinyQBN may be perfect for something I'm trying to make which is
why I was trying to get it up and running etc.

So honestly I don't think you can have too many pictures :P As a
non-programmer, every bit of visuals helps. Particularly for the content of
passages would be helpful (you do this a bit already, but even more would
be good) e.g at the end of the tutorial something like, your passages
should look like this: cue picture!

Haha yeah it's not necessarily general knowledge. I did know it :)
